# Generated by Django 3.0.5 on 2022-02-25 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('bank_id', models.IntegerField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('ifsc', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.IntegerField(primary_key=True, serialize=False)),
                ('loan_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('loan_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='Multiple_App.Loan')),
                ('bank_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Multiple_App.Bank')),
                ('customer_name', models.CharField(max_length=30)),
                ('account_number', models.IntegerField(unique=True)),
            ],
            bases=('Multiple_App.bank', 'Multiple_App.loan'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('loan_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='Multiple_App.Loan')),
                ('bank_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Multiple_App.Bank')),
                ('emp_name', models.CharField(max_length=30)),
                ('account_number', models.IntegerField(unique=True)),
            ],
            bases=('Multiple_App.bank', 'Multiple_App.loan'),
        ),
    ]
